ptf ~
~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ 
~   hk1 ~ ~   hk1 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ 
~   hk1 ~ ~   hk1 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk2 ~ ~   hk3 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk2 ~ ~   hk3 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk2 ~ ~   hk3 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk2 ~ ~   hk3 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk2 ~ ~   hk3 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk3 ~ ~   hk3 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk3 ~ ~   hk4 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk3 ~ ~   hk4 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk3 ~ ~   hk4 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk3 ~ ~   hk4 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk3 ~ ~   hk4 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk3 ~ ~   hk4 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk1 ~ ~   hk1 ~ ~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk4 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk2 ~ ~   hk1 ~ ~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk4 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk4 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk4 ~ ~   hk5 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ 
~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk5 ~ ~   hk4 ~ ~   hk5 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ 
~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk5 ~ ~   hk6 ~ ~   hk4 ~ ~   hk5 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ 
~   hk2 ~ ~   hk2 ~ ~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk6 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk5 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ 
~   hk2 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk5 ~ ~   hk4 ~ 
~   hk1 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk4 ~ ~   hk5 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ 
~   hk1 ~ ~   hk1 ~ ~   hk3 ~ ~   hk3 ~ ~   hk3 ~ ~   hk4 ~ ~   hk4 ~ ~   hk5 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk3 ~ 
~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk3 ~ 
~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk4 ~ ~   hk4 ~ ~   hk4 ~ ~   hk5 ~ ~   hk5 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk3 ~ ~   hk1 ~ 
~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk3 ~ ~   hk4 ~ ~   hk4 ~ ~   hk5 ~ ~   hk5 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk4 ~ ~   hk3 ~ ~   hk1 ~ 
~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk4 ~ ~   hk4 ~ ~   hk5 ~ ~   hk5 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk4 ~ ~   hk1 ~ ~   hk1 ~ 
~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk4 ~ ~   hk4 ~ ~   hk5 ~ ~   hk5 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk5 ~ ~   hk5 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ 
~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk3 ~ ~   hk5 ~ ~   hk5 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk6 ~ ~   hk5 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ ~   hk1 ~ 
